# Generated by Django 5.1.4 on 2025-01-10 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('Done', 'Done')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
